INSERT INTO Opettaja (nimi, salasana) VALUES ('Santeri', 'Santeri123');
INSERT INTO Opettaja (nimi, salasana) VALUES ('Santeri2', 'Santeri123');
INSERT INTO Opettaja (nimi, salasana) VALUES ('Santeri3', 'Santeri123');

INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe2', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe3', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe4', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe5', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe6', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe7', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe8', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe9', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe10', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe11', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe12', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe13', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe14', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe15', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe16', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe17', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe18', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe19', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe20', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe21', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe22', 'Tämä on testi ehheh');
INSERT INTO Tyoaihe (nimi, kuvaus) VALUES ('Työaihe23', 'Tämä on testi ehheh');

INSERT INTO Suoritus (tyoaihe_id, opettaja_id, suoritusaika, arvosana) VALUES (10, 4, 120, 3);
INSERT INTO Suoritus (tyoaihe_id, opettaja_id, suoritusaika, arvosana) VALUES (10, 4, 90, 1);
INSERT INTO Suoritus (tyoaihe_id, opettaja_id, suoritusaika, arvosana) VALUES (10, 4, 13, 0);
INSERT INTO Suoritus (tyoaihe_id, opettaja_id, suoritusaika, arvosana) VALUES (10, 4, 50, 5);
INSERT INTO Suoritus (tyoaihe_id, opettaja_id, suoritusaika, arvosana) VALUES (10, 4, 70, 3);
INSERT INTO Suoritus (tyoaihe_id, opettaja_id, suoritusaika, arvosana) VALUES (10, 4, 80, 4);
INSERT INTO Suoritus (tyoaihe_id, opettaja_id, suoritusaika, arvosana) VALUES (10, 4, 90, 4);


INSERT INTO Laboratoriokurssi (opettaja_id, nimi, kuvaus) VALUES (1, 'testikurssi123', Tämä on testikurssi);
INSERT INTO Laboratoriokurssi (opettaja_id, nimi, kuvaus) VALUES (2, 'testikurssi12', Tämä on testikurssi);
INSERT INTO Laboratoriokurssi (opettaja_id, nimi, kuvaus) VALUES (3, 'testikurssi1233', Tämä on testikurssi);
INSERT INTO Laboratoriokurssi (opettaja_id, nimi, kuvaus) VALUES (2, 'testikurssi2', Tämä on testikurssi);
INSERT INTO Laboratoriokurssi (opettaja_id, nimi, kuvaus) VALUES (1, 'testikurssi3', Tämä on testikurssi);
INSERT INTO Laboratoriokurssi (opettaja_id, nimi, kuvaus) VALUES (2, 'testikurssi4', Tämä on testikurssi);
INSERT INTO Laboratoriokurssi (opettaja_id, nimi, kuvaus) VALUES (3, 'testikurssi5', Tämä on testikurssi);
INSERT INTO Laboratoriokurssi (opettaja_id, nimi, kuvaus) VALUES (2, 'testikurssi6', Tämä on testikurssi);
INSERT INTO Laboratoriokurssi (opettaja_id, nimi, kuvaus) VALUES (1, 'testikurssi7', Tämä on testikurssi);
INSERT INTO Laboratoriokurssi (opettaja_id, nimi, kuvaus) VALUES (2, 'testikurssi8', Tämä on testikurssi);
INSERT INTO Laboratoriokurssi (opettaja_id, nimi, kuvaus) VALUES (3, 'testikurssi9', Tämä on testikurssi);
INSERT INTO Laboratoriokurssi (opettaja_id, nimi, kuvaus) VALUES (1, 'testikurssi0', Tämä on testikurssi);


INSERT INTO Labratyoaihe VALUES (1, 1);
INSERT INTO Labratyoaihe VALUES (2, 2); 
INSERT INTO Labratyoaihe VALUES (3, 3); 
INSERT INTO Labratyoaihe VALUES (4, 4); 
INSERT INTO Labratyoaihe VALUES (5, 5); 
INSERT INTO Labratyoaihe VALUES (6, 6); 
INSERT INTO Labratyoaihe VALUES (7, 7); 
INSERT INTO Labratyoaihe VALUES (8, 8); 
INSERT INTO Labratyoaihe VALUES (9, 9); 
INSERT INTO Labratyoaihe VALUES (10, 10); 
INSERT INTO Labratyoaihe VALUES (11, 11); 
INSERT INTO Labratyoaihe VALUES (12, 12); 
INSERT INTO Labratyoaihe VALUES (13, 13); 
INSERT INTO Labratyoaihe VALUES (14, 14); 
INSERT INTO Labratyoaihe VALUES (15, 15);
INSERT INTO Labratyoaihe VALUES (7, 17); 
INSERT INTO Labratyoaihe VALUES (7, 17); 
INSERT INTO Labratyoaihe VALUES (8, 17); 
INSERT INTO Labratyoaihe VALUES (8, 17); 
INSERT INTO Labratyoaihe VALUES (9, 17); 
INSERT INTO Labratyoaihe VALUES (9, 17); 
INSERT INTO Labratyoaihe VALUES (10, 17);  
INSERT INTO Labratyoaihe VALUES (10, 25);
INSERT INTO Labratyoaihe VALUES (11, 25);
INSERT INTO Labratyoaihe VALUES (12, 25);
INSERT INTO Labratyoaihe VALUES (13, 25);
INSERT INTO Labratyoaihe VALUES (14, 25);
INSERT INTO Labratyoaihe VALUES (15, 25);
INSERT INTO Labratyoaihe VALUES (11, 24);